### ISSUE TITLE
Wire Frames

### ISSUE THREAD

**Issue by EmileeA** [nss-evening-cohort-10/nutshell-star-destroyer#11]
![homepage-together](https://user-images.githubusercontent.com/54127296/68829901-d1402580-066f-11ea-9451-7200d0c79192.PNG)

**Comment by mariabrock** [comment]
![dropdown-menu-together](https://user-images.githubusercontent.com/54127296/68829909-d7ce9d00-066f-11ea-83ec-6ff8fa0455a6.PNG)

**Comment by mariabrock** [comment]
![personnel wireframe](https://user-images.githubusercontent.com/54127296/68829921-df8e4180-066f-11ea-97a9-736165409bb8.PNG)

**Comment by mariabrock** [comment]
![weapons wireframe](https://user-images.githubusercontent.com/54127296/68829931-e6b54f80-066f-11ea-8ba5-c9997457a7a7.PNG)

**Comment by mariabrock** [comment]
![weapons-card-before-click](https://user-images.githubusercontent.com/54127296/68829940-ed43c700-066f-11ea-9f2c-c1bd3c3d8724.PNG)

**Comment by mariabrock** [comment]
![weapons-card-after-click](https://user-images.githubusercontent.com/54127296/68829946-f3d23e80-066f-11ea-835d-eb9897898669.PNG)

**Comment by mariabrock** [comment]
![enemies wireframe](https://user-images.githubusercontent.com/54127296/68829954-f896f280-066f-11ea-9192-aa059e7fd63b.PNG)

**Comment by mariabrock** [comment]
![enemies-large-card](https://user-images.githubusercontent.com/54127296/68829964-fe8cd380-066f-11ea-8167-4130c515f06d.PNG)

**Comment by mariabrock** [comment]
![sectors wireframe](https://user-images.githubusercontent.com/54127296/68829978-09dfff00-0670-11ea-940a-8c63abf65388.PNG)
