### ISSUE TITLE
Personnel: Delete

### ISSUE THREAD

**Issue by EmileeA** [nss-evening-cohort-10/nutshell-star-destroyer#13]
# User Story
* As a user, I should be able to remove Personnel.

# AC
GIVEN the user is logged in and visits the Personnel page
WHEN the user clicks the delete button on the personnel card
THEN the person is removed from firebase
AND update the DOM

# Delete
* this satisfies the DELETE component of C.R.U.D.

1. In helpers/data personnelData.js:
* Create an axios call that allows user to delete personnel members from firebase and the DOM - add this line beneath your getPersonnelData function:
`const deletePersonData = (personId) => axios.delete(`${baseUrl}/personnel/${personId}.json`);`
* add deletePersonData to your default export line
2. In javascripts/components/Personnel/personnel.js:
* import deletePersonData into this file

* write a function called deletePersonOnClick that accepts an event (e) as a parameter that, when initiated, collects the personId of the card clicked on and passes the personId into the deletePersonData that looks something like this:

	`const deletePersonOnClick = (e) => {
	  e.preventDefault();
	  personnelDelete.deletePersonData(e.target.id)
	    .then(() => {
	      // eslint-disable-next-line no-use-before-define
	      displayCrew(personId);
	    })
	    .catch((error) => console.error(error));
	};`
* use jQuery to trigger the function on button click in this fashion:
`<button class="btn btn-danger deletePerson" id="${person.id}"></button>`
`$('body').on('click', '.deletePerson', (e) => deletePersonOnClick(e));`
* clicking the "Delete" button will grab the personId of the crew member and remove that data from the page and firebase
* once person's card and data are removed, the displayCrew function should run again and re-print all cards to the screen

**Comment by EmileeA** [comment]
Button:
https://getbootstrap.com/docs/4.3/components/buttons/#examples
Modal:
https://getbootstrap.com/docs/4.3/components/modal/#modal-components

**Comment by rtate2** [comment]
**Delete Button Example**

<img width="351" alt="Star-Destroyer-deleteButton" src="https://user-images.githubusercontent.com/54008854/69484382-37f3da80-0df8-11ea-88e9-9bad5b62ca87.png">
