### ISSUE TITLE
Personnel: Update

### ISSUE THREAD

**Issue by EmileeA** [nss-evening-cohort-10/nutshell-star-destroyer#14]
# User Story
* As a user, I should be able to edit Personnel.

# AC
GIVEN a user wants to update Personnel
WHEN the user clicks on edit
THEN a form should be presented to the user
AND after the user edits the information and selects save button the data should update in firebase
AND the DOM is updated

# Dev Notes
* this satisfies the UPDATE component of C.R.U.D.
1. In helpers/data/personnelData.js
* place this line beneath your createNewPerson function:
`const updatePersonnel = (personId, updatedPerson) => axios.put(`${baseUrl}/personnel/${personId}.json`, updatedPerson);`
* add updatePersonnel to your export default line
2. In javascripts/components/Personnel/personnel.js:
* import updatePersonnel into this file
* when the edit button on the personnel's card is pressed, a modal should appear with that crew members information displayed: Name, Person Photo, Sector and Weapon.
*the modal's "Save Changes" button should have an id of **update-personnel**
*using jQuery, assign the update function to occur when user clicks on the "Save Changes" button within the modal something like this:

`$('body').on('click', '#update-personnel', updatingPersonnel);`

*write a function called updatePerson that accepts an event (e) that, when initiated, gathers the value of the modal's inputs and updates firebase with this data by utilizing the updatePersonnel function

	`const updatingPersonnel = (personId, newPersonData) => new Promise((resolve, reject) => {
	  axios.get(`${baseUrl}/personnel/${personId}.json`)
	    .then((result) => {
	      const personObject = result.data;
	      personObject.name = newPersonData;
	      personObject.personImg = newPersonData
              personObject.position = newPersonData;
	      updatePerson(personId, person);
	      resolve();
	    })
            .then(() => {
            personnelDisplay.displayCrew(personId);
            })
	    .catch((error) => reject(error));
	});`
* once person's card and data are updated, the displayCrew function should run again and re-print all cards to the screen. the card that has been modified should reflect the changes made

**Comment by ghost** [comment]
EDIT does not work. When "Edit" button is clicked a blank modal generates, when a pre-printed modal should generate.

**Comment by rtate2** [comment]
**Edit modal example**
<img width="500" alt="Star-Destroyer-editModal" src="https://user-images.githubusercontent.com/54008854/69505293-cea2c300-0eee-11ea-9da9-65de6eba06aa.png">
