### ISSUE TITLE
Personnel: Read

### ISSUE THREAD

**Issue by EmileeA** [nss-evening-cohort-10/nutshell-star-destroyer#15]
# User Story
* As a user, I should be able to view all Personnel.

# AC
WHEN the user visits the Personnel page
THEN they will be able to see all of the personnel
AND there will be two in the row and follow the mockups

# Dev Notes
* this satisfies the `READ` component of the C.R.U.D.

1.  Wireframes
 * see the wireframe below for the basic structure of the page

2. Creating `.json` data
* create a `personnel.json` seed data in the `db` folder of your project
* create 4 personnel following this format:

`{`
  `"person": {`
    `"id": "",`
     `"name": "",`
    `"secorId": "",`
    `"weaponId": "",`
  `},`
`}`

* import this data into firebase

3. Helpers folder files/retrieving from firebase

* create a `personnelData.js` file in the `javascripts/helpers/data` to pull the JSON data from firebase
* the first 4 lines of code at the top of this file are:

`import axios from 'axios';`
`import apiKeys from '.../apiKeys.json';`
`import 'firebase/auth';`

`const baseUrl = apiKeys.firebaseKeys.databaseURL;`

* the function to pull this data down requires an axious.get() . It should look something like this:

`const getPersonnelData = () => new Promise((resolve, reject) => {
axios.get``(`${baseUrl}/personnel.json`)`
    `.then((response) => {`
      `const demPersonnel= response.data;`
      `const personnel = [];`
      `Object.keys(demPersonnel).forEach((personId) => {`
        `demPersonnel[personId].id = personId;`
        `personnel.push(demPersonnel[personId]);`
      `});`
      `resolve(personnel);`
    `})`
    `.catch((error) => reject(error));`
`});`

4. Components folders and files:
* create a `Personnel` folder inside javascripts/components and place two files within it: `personnel.js` and `personnel.scss`
* link the `personnel.scss` file to the `personnel.js` by placing this line at the top of your `personnel.js`:

`import './personnel.scss';`

* at the bottom of `personnel.js` place this line:

`export default { displayCrew };`

* inside your `main.js`, at the top of the page, place this line:

`import personnelDisplay from './components/Personnel/personnel';`

*and within the `init` function, place this line:

`personnelDisplay.displayCrew();`

5 Printing the data to the DOM
* the `personnel.js` create a function called `displayCrew` that calls the getPersonnelData and runs it through a forEach loop to create bootstrap cards; this will print out to the `personnel` div within the index.html - this will be printed to the DOM upon page load using printToDom

* `displayCrew` will display an image of the personnel and details within it, size (in parsecs), a button allowing editing of the personnel data, and button allowing personnel deletion all housed within a card(see Bootstrap link below for card)
- the buttons will not display if the user is't logged in

* at the top of this page, there should be a button that allows the user to create a new personnel of space, see wireframe for example of modal/form; dynamically print this with `displayCrew`
- again, the button will not display if the user isn't logged in

- If the userobject is found with firebase.auth().currentUser, then add the edit and delete buttons to the domstring. use this snippet in createCrewCard
```const user = firebase.auth().currentUser;
if (user != null) {
 // do stuff
}
```

* ideally utilize bootstrap elements to achieve what the wireframe advertises. for color reference visit the official Imperial Style guide listed below.
* "Personnel" centered as H1 tag on page load

**Comment by EmileeA** [comment]
![image](https://user-images.githubusercontent.com/36553398/68978482-7f5ae500-07c0-11ea-8378-29f5d8bd1299.png)

**Comment by EmileeA** [comment]
Imperial Style Guide:
https://imperialstyleguide.com/

bootstrap css source code:
https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.css

possible bootstrap layout options:
https://getbootstrap.com/docs/4.3/components/card/#image-overlays
https://getbootstrap.com/docs/4.3/components/jumbotron/
https://getbootstrap.com/docs/4.3/components/buttons/#examples

form:
https://getbootstrap.com/docs/4.3/components/forms/#form-grid

modal:
https://getbootstrap.com/docs/4.3/components/modal/#vertically-centered

**Comment by EmileeA** [comment]
![image](https://user-images.githubusercontent.com/36553398/68982670-8e945f80-07cd-11ea-8acd-6c218973d4f5.png)

**Comment by ghost** [comment]
Personnel is reading from database correctly, but CRUD buttons should not be displaying unless logged in.
