### ISSUE TITLE
Sectors: Read

### ISSUE THREAD

**Issue by mariabrock** [nss-evening-cohort-10/nutshell-star-destroyer#17]
# User Story
As a user, I should be able to view all the Planetary Sectors.

# AC
***WHEN*** a user is logged in
***THEN*** they should only be able to read info on each sector
***AND*** navigate/search by keyword

# Dev Notes
* this satisfies the `READ` component of the C.R.U.D.

1.  Wireframes
 * see the wireframe below for the basic structure of the page

1. Helpers folder files/retreiving from firebase

* create a `sectorsData.js` file in the `javascripts/helpers/data` to pull the JSON data from firebase
* the first 4 lines of code at the top of this file are:

`import axios from 'axios';`
`import apiKeys from '.../apiKeys.json';`
`import 'firebase/auth';`

`const baseUrl = apiKeys.firebaseKeys.databaseURL;`

* the function to pull this data down requires an axious.get() . It should look something like this:

`const sectorsDataBySectorId = (sectorId) => new Promise((resolve, reject) => {`
  `axios.get(`${baseUrl}/sectors.json?orderBy="sectorId"&equalTo="${sectorId}"`)`
    `.then((response) => {`
      `const demSectors = response.data;`
      `const sectorss = [];`
      `Object.keys(demSectors).forEach((scId) => {`
        `demSectors[emId].id = scId;`
        `employees.push(demSectors[scId]);`
      `});`
      `resolve(employees);`
    `})`
    `.catch((error) => reject(error));`
`});`

1. Components folders and files:
* create an `Sectors` folder inside javascripts/components and place two files within it: `sectors.js` and `sectors.scss`
* like the `sectors.scss` file to the `sectors.js` by placing this line at the top of your `sectors.js`:

`import './sectors.scss';`

* at the bottom of `sectors.js` place this line:

`export default { displaySectors };`

* inside your `main.js`, at the top of the page, place this line:

`import sectors from './components/Sectors/sectors';`

and within the `init` function, place this line:

`sectors.displaySectors()'`

1. Printing the data to the DOM
* the `sectors.js` will contain a function called `displaySectors` that prints to a `sectors` div within the `logged-in` div in index.html when the nav icon of Sectors or the Reset Data buttons of the Sectors page are clicked

* `displaySectors` will display an image of the sector and systems within it, size (in parsecs), a description of important places, a button allowing editing of the sector data, and button allowing sector deletion all housed within a card(see Bootstrap link below for card)

* at the top of this page, there should be a button that allows the user to create a new sector of space, see wireframe for example of modal/form; dynamically print this with `displaySectors`

* ideally utilize bootstrap elements to achieve what the wireframe advertises. for color reference visit the official Imperial Style guide listed below. you may have to adapt the source code of the elements in your `sectors.scss` . the bootstrap source code can be found in the link below as well.

**Comment by mariabrock** [comment]
![sectors wireframe](https://user-images.githubusercontent.com/54127296/68908971-71e72180-0712-11ea-9788-d7cf66eedfdd.PNG)

**Comment by mariabrock** [comment]
![sector-keys](https://user-images.githubusercontent.com/54127296/68908979-7a3f5c80-0712-11ea-9812-560b03620bf7.PNG)

**Comment by mariabrock** [comment]
Imperial Style Guide:
https://imperialstyleguide.com/

bootstrap css source code:
https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.css

possible bootstrap layout options:
https://getbootstrap.com/docs/4.3/components/card/#image-overlays
https://getbootstrap.com/docs/4.3/components/jumbotron/
https://getbootstrap.com/docs/4.3/components/buttons/#examples

form:
https://getbootstrap.com/docs/4.3/components/forms/#form-grid

modal:
https://getbootstrap.com/docs/4.3/components/modal/#vertically-centered

**Comment by ghost** [comment]
CRUD buttons should only display on login. Change "Galaxy Tab" to instead say Sector. Changes to make to code:

1. Create if/else statement in `displayAllSectors` function to only print CRUD buttons for each card when a user is recognized. Should look something along the lines of:
```
const displayAllSectors = () => {
  sectorsData
    .getAllSectors()
    .then((sectors) => {
      let domString = '';
      const user = firebase.auth().currentUser;
      if (user != null) {
 domString += '<button type="button" class="btn btn-outline-light" id="addSectorData" data-toggle="modal" data-target="#addSectorDataModal">Add Data</button>';
      domString += '<div class="row">';
      sectors.forEach((sector) => {
        domString += '<div class="col-sm-6">';
        domString += '<div class="card">';
        domString += '<div class="card-body">';
        domString += `<h5 class="card-title">${sector.name}</h5>
            <p class="card-text">${sector.info}</p>
            <p class="card-text"><small class="text-muted">${sector.size} 
            </small></p>
            <img src="${sector.sectorImg}" class="card-img-top" alt="...">
            <button type="button" class="btn btn-light" 
             id="update">Update</button>
            <button type="button" class="btn btn-danger" 
             id="delete">Delete</button>
            </div>
          </div>
        </div>
      </div>
      `;
}
      else {
      domString += '<div class="row">';
      sectors.forEach((sector) => {
        domString += '<div class="col-sm-6">';
        domString += '<div class="card">';
        domString += '<div class="card-body">';
        domString += `<h5 class="card-title">${sector.name}</h5>
            <p class="card-text">${sector.info}</p>
            <p class="card-text"><small class="text-muted">${sector.size}</small></p>
            <img src="${sector.sectorImg}" class="card-img-top" alt="...">
            </div>
          </div>
        </div>
      </div>
      `;
}
      });
      utilities.printToDom('sectors', domString);
      // $('body').on('click', '#update', addSectorInfo);
      // $('body').on('click', '#delete', deleteSector);
    })
    .catch((error) => console.error(error));
};
```
1. `displayAllSectors` function call should be removed from main.js, and instead called in `const attachEvents` in ourNavbar.js on both on login and logout. Should look something along the lines of:
```
import sector from '../../components/Sectors/sector.js'

const attachEvents = () => {
  logoutButton.click((e) => {
    e.preventDefault();
    firebase.auth().signOut()
      .then(() => {
       sector.displayAllSectors();
      }).catch((err) => console.error('you still logged in', err));
  });
  loginButton.click((e) => {
    e.preventDefault();
    auth.signMeIn();
    sector.displayAllSectors();
  });
};
```
1. Edit hardcoded navbar to replace "Galaxy" copy in tab to instead say "Sectors" for less confusion
