### ISSUE TITLE
Sectors: Update

### ISSUE THREAD

**Issue by mariabrock** [nss-evening-cohort-10/nutshell-star-destroyer#18]
# User Story
As a user, I should be able to edit a Planetary Sector.

# AC
***WHEN*** a user clicks the `Update` button on a data entry
***THEN*** a modal with a form nested inside it opens
***AND*** it displays information relevant to that entry
***AND*** the user should be able to input new information
***AND*** when the form has been submitted the information on the page updates

# Dev Notes
*this satisfies the `UPDATE` component of C.R.U.D.

1. Wireframes
* see the wireframe below for the basic structure of the modal that should appear after the user clicks the `Update` button

2. Modal and form
* use bootstrap for modal and form nested within the modal to allow user to change data in the categories given

* for styling please reference the Imperial style guide below

* the event listener for the `Update` button should look something like this:
`$('#sectors').on('click', '.print-sector', buildSector);`

3. Saving Data
* when save button is clicked, write a function named `updateSector`  in `sectors.js`

* `updateSector` will update the entry in the JSON in firebase

**Comment by mariabrock** [comment]
Button:
https://getbootstrap.com/docs/4.3/components/buttons/#examples
Form:
https://getbootstrap.com/docs/4.3/components/forms/#layout
Modal:
https://getbootstrap.com/docs/4.3/components/modal/#modal-components

**Comment by mariabrock** [comment]
![create-modal-wireframe](https://user-images.githubusercontent.com/54127296/68916196-77e8fc80-072a-11ea-9b56-7f1ec68f4b63.PNG)

**Comment by mariabrock** [comment]
![update-delete-entry-wireframe](https://user-images.githubusercontent.com/54127296/68995553-c85c7900-0854-11ea-9243-ffff57aceadc.PNG)

**Comment by ghost** [comment]
1. in sectorsData.js, write a function to get the sectors by id so we can use it in our function that will prepopulate the modal upon clicking the "Edit" button in each card, with all the key value pairs of the selected sector:

```
const getSectorByID = (id) => new Promise((resolve, reject) => {
  axios.get(`${baseUrl}/sectors/${id}.json`)
    .then((response) => {
      resolve(response.data);
    })
    .catch((error) => reject(error));
});
```

2. Then write an update function that will take a sector Id and the value of an updated sector, and pass both through an `axios.put` function to recognize the selected sectors id, and pass in the new values entered into the modal that will pop up on clicking the "Edit" button for each card, and update those new values in Firebase:
`const editSector = (id, updatedFood) => axios.put(`${baseUrl}/food/${id}.json`, updatedFood);`

3. Create a `const sectorModal` function in sectors.js that will print a modal with placeholder values using a ternary function that will be shared by the "Add Data" button and "Edit" button on each card. Should look something along the lines of:

```
const sectorModal = (sector) => {
  const domString = `<div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <a class="navbar-brand d-flex" href="#">
            <img id="panam-logo" src="https://vignette.wikia.nocookie.net/starwars/images/2/2e/Imperial_Emblem.svg/revision/latest/scale-to-width-down/200?cb=20080220004323" alt="" style="max-width: 180px; align-items: left; justify-content: left;">
        </a>
        <h5 class="modal-title" id="exampleModalLabel" style="margin-top:34px; margin-right:180px; color: #1c69b1;">New Sector</h5>
      </div>
      <div class="modal-body">
        <form>
          <div class="form-group>
            <label for="name" class="col-form-label">Name:</label>
            <input type="text" class="form-control" id="name" value="${sector.name ? sector.name : ''}">
          </div>
          <div class="form-group">
            <label for="size" class="col-form-label">Size:</label>
            <input type="text" class="form-control" id="size" value="${sector.size ? sector.size : ''}"></input>
          </div>
          <div class="form-group">
            <label for="sectorImg" class="col-form-label">Image URL:</label>
            <input type="text" class="form-control" id="sectorImg" value="${sector.sectorImg ? sector.sectorImg : ''}"></input>
          </div>
          <div class="form-group">
            <label for="isAlly" class="col-form-label">Ally?:</label>
            <input type="text" class="form-control" id="isAlly" value="${sector.isAlly ? sector.isAlly : ''}"></input>
          </div>
          <div class="form-group">
            <label for="info" class="col-form-label">Menu Category:</label>
            <input type="text" class="form-control" id="info" value="${sector.info ? sector.info : ''}"></input>
          </div>
        </form>
      </div>
      <div class="modal-footer text-center" id="${sector.id}">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="button" id="${sector.id ? 'update' : 'submit'}" class="btn btn-danger">Submit</button>
      </div>
    </div>
  </div>`;
  return domString;
};
```
The ternary values in the function above will conditionally print a value in the input form of the selected sector, and there's a ternary value for the id of the "Submit" button, which will be incorporated so the same modal can be used for both ADD and CREATE functionality, by targeting different IDs for each event listener.

4. Create a function in sectors.js to pass through the value of the new edited sector, based on the value of the text in the input form of the modal referenced above. Code should look something along the lines of:

```
const editedSector = (e) => {
  e.stopImmediatePropagation();
  const editedSectorId = e.target.parentNode.id;
  const updatedSector = {
    name: $('#name').val(),
    size: $('#size').val(),
    sectorImg: $('#sectorImg').val(),
    isAlly: $('#isAlly').val(),
    info: $('#info').val(),
  };
  sectorData.editSector(editedSectorId, updatedSector)
    .then(() => {
      $('#exampleModal').modal('hide');
      // eslint-disable-next-line no-use-before-define
      displayAllSectors();
    })
    .catch((error) => console.error(error));
};
```
5. Create a function that will print the modal info from `sectorModal` to the blank modal div with the id `#exampleModal` that will be hardcoded in the index.html, and reference the event listener that will call the function for the CREATE component:

```
const newSectorDetails = (sector) => {
  let domString = '';
  domString += sectorModal(sector);
  utilities.printToDom('exampleModal', domString);
  $('#submit').click(addNewSector);
};
```

6. Then, create a function that will take the id of the selected Sector, retrieve it's data from firebase based on id, and populate the modal inputs with prepopulated values pulled from firebase. Then the function will create an event listener for the "Submit" button on the modal and call the `editedSector` function created above:

```
const updateSectorValues = (e) => {
  sectorData.getSectorByID(e.target.id)
    .then((response) => {
      $('#exampleModal').modal('show');
      response.id = e.target.id;
      newSectorDetails(response);
      // eslint-disable-next-line no-use-before-define
      $('#update').click(editedSector);
    });
};
```

7. Finally create an event listener at the end of `displayAllSectors` that will pull all the functions above together by calling `updateSectorValues` on click of the "Edit" button:
`$(document.body).on('click', '.edit-sector', updateSectorValues);`
