### ISSUE TITLE
Enemies-Create

### ISSUE THREAD

**Issue by williaj615** [nss-evening-cohort-10/nutshell-star-destroyer#22]
# User Story
As a logged in user, I should be able to create new enemy when I click on the `add enemy` button on the top of the page.

# AC
**WHEN** a logged in user clicks on the `add enemy` button at the top of the page
**THEN** a modal will present to the page with the input fields corresponding to the labels to type in the enemy values 
**THEN** the user will click the `Save New Enemy` button and the modal leaves the page
**THEN**  the new enemy is added to the firebase and the new enemy card appears in the `enemiespage` div on the page

# Dev Notes
* Create a `ra-enemy-CREATE` branch
*Confirm the `axios.post` is working with a `console.log` in the `enemies.js` `.then`
* Confirm the `Add New Enemy` button is only visible to logged in users.
* Update the html with modal template to print custom modal info to the 
`allModalsDiv`.
* Confirm when user clicks on the `Add New Enemy`  button that the modal displays in the `allModalsDiv` div for the user to input the values of the new enemy
* Confirm this line in `enemies.js` : `$('#savenewenemy').click(addNewEnemy)` runs the `AddNewEnemy` function and the new enemy is added to firebase
* Make sure `buildEnemies` is called to reflect the new enemy is on the page with the already existing ones.
* Confirm #23

**Comment by ghost** [comment]
<img width="328" alt="nutshellAddModal" src="https://user-images.githubusercontent.com/54124397/69482887-784a5d00-0de6-11ea-884f-c1fad474c287.PNG">

Add works only when you click "Save New Enemy" button in modal. "Save Changes" button doesn't work and should be removed. Modal should display with empty inputs when you click "Add New Enemy", but currently the modal will show whatever text you entered into the input form last. "Add New Enemy"  button should only display when the user is logged in.
