### ISSUE TITLE
Enemies-Read

### ISSUE THREAD

**Issue by williaj615** [nss-evening-cohort-10/nutshell-star-destroyer#23]
# User Story
As a user, I should be able to view all enemies on page load. 

# AC
**WHEN** the page loads the user will see 9 enemies on the page, 3 per row centered printed to the `enemiesPage` div d-flex.

# Dev Notes
* Create` ra-enemies-READ` branch
*Check the enemyData.js file containing the `axios.get` place a `console.log(response.data)` to confirm data is reading correctly from firebase.
* Check `enemies.js` file and re-factor the  `enemiesBuilder` function to loop over the `enemies. json` data from firebase to build up the enemy cards printing to the `enemiesPage`  div 3 per row d-flex.
Review position of enemy cards nothing in the `ememy.scss file.
* Add if/else statement in `enemiesBuilder` domString that will only show the `Delete` and `Edit` buttons do not show on read as they currently were in Part 1

**Comment by ghost** [comment]
Fix styling. CRUD buttons should only show when the user is logged in.
