### ISSUE TITLE
Enemies-Delete

### ISSUE THREAD

**Issue by williaj615** [nss-evening-cohort-10/nutshell-star-destroyer#25]
# User Story
As a logged in user, I should be able to click on the `delete` on a enemy card and the card disappears from the page.

# AC
**WHEN**  a user clicks the delete button on an enemy's card
**THEN** the enemy should be deleted from firebase
**AND** the page reflects this action with the enemy no longer on it

# Dev Notes
** Create `ra-enemy-Delete` branch
*Confirm the `Delete` and `Edit` show only on logged in user and no longer on READ #23 
--This Code below currently works --
* In enemiesData.js add a `deleteEnemy` function
* In enemies.js add a `delete` button to the cards of the enemies
* Add event listeners to delete buttons to call enemiesData.deleteEnemy

**Comment by ghost** [comment]
Delete works, but the Delete button should only display on login.
