### ISSUE TITLE
Weapons: Seed Data

### ISSUE THREAD

**Issue by jthielman** [nss-evening-cohort-10/nutshell-star-destroyer#26]
# User story
As a developer, I need some seed data to work with so that as I write functions, I can tell that the right stuff is happening.

# AC
**When** I open the firebase console
**Then** I should find weapons data with a structure corresponding to the ERD.
**And** that data should have come from a data file in the directory so I can reseed when necessary.

# Dev Notes
Put data files into `./db`.  Call it `weapons.json`. Here's a sample object:
```
{
  "weapon1": {
    "name": "XX-9 heavy turbolaser",
    "isActive": true,
    "type": "ship-mounted"
  },
}
```

**Comment by mariabrock** [comment]
![weapons wireframe](https://user-images.githubusercontent.com/54127296/68828745-68a37980-066c-11ea-8ce0-325a6c185ceb.PNG)

**Comment by mariabrock** [comment]
![weapons-card-before-click](https://user-images.githubusercontent.com/54127296/68828752-6e00c400-066c-11ea-8f01-adf8b73c877a.PNG)

**Comment by mariabrock** [comment]
![weapons-card-after-click](https://user-images.githubusercontent.com/54127296/68828765-72c57800-066c-11ea-8c55-e3a3d56382f1.PNG)
