### ISSUE TITLE
Weapons: Create

### ISSUE THREAD

**Issue by jthielman** [nss-evening-cohort-10/nutshell-star-destroyer#28]
**User Story**
As a user I should be able to add weapons as needed.

**AC**

**GIVEN** the user is logged in and visits the Weapons page
**WHEN** they click the "Add " button
**THEN** there will be a modal to create a new weapon

**WHEN** the "save" button is clicked
**THEN** the new weapon will be found in weapons collection in firebase
**AND** the dom will be updated from firebase

**Dev Notes**

* Create an axios call in the weaponsData.js (addNewWeapon) file that allows user to post the object to firebase (post)

* addNewWeapon will take (newWeapon) as a parameter

* Create the "Add" button below the card that prepopulates a modal in index.html for the user to input information to create a new weapon within the specific category

* Create addWeapon function within components/Weapons/weapons.js that reads the values from the input fields to create a new weapon object, and then pass the object to addNewWeapon

* update dom with createWeaponCard function

**Styling**

The card styling will be the same within a bootstrap card

**Comment by ghost** [comment]
CREATE works, but the "Add Weapon" button should only display when logged in.
