### ISSUE TITLE
Enemies-Seed Data

### ISSUE THREAD

**Issue by williaj615** [nss-evening-cohort-10/nutshell-star-destroyer#31]
# User Story
As a developer I should have some enemy data for my database.

# AC
**WHEN** I open my database 
**THEN** I should see enemy data present.

# Dev Notes
* Create JSON data to import into Firebase: {
  "enemy1": {
    "id": "",
    "imageUrl
    "name": "",
    "base-sector": "",
    "LKL": "",
    "isDead": "",
    "isCaptured": ""
  },
}
* 6 enemies overall for seed data

**Comment by mariabrock** [comment]
![enemies wireframe](https://user-images.githubusercontent.com/54127296/68828815-9688be00-066c-11ea-811a-72c714060ef0.PNG)

**Comment by mariabrock** [comment]
![enemies-large-card](https://user-images.githubusercontent.com/54127296/68828841-9e486280-066c-11ea-9a66-39e0701e120e.PNG)
