### ISSUE TITLE
Home Page: NavBar

### ISSUE THREAD

**Issue by EmileeA** [nss-evening-cohort-10/nutshell-star-destroyer#34]
# User Story
When a user logs in, they should see a navbar across all pages with the Imperial logo and an option to click a drop-down menu. There should be a search bar in the nav that allows them to search via keyword.

# AC
***WHEN*** the user loads the homepage
***THEN*** they should see a navbar on each page
***AND*** it will have a search bar in the center
***AND*** they can search by keyword
***AND*** it will have a drop-down menu in the top left
***AND*** it will have the imperial logo in the top right

# Dev Notes
* navbar should be seen across everypage
* use bootstrap for the navbar
* use the imperial styling guide website for images and colors
* the drop down menu will be based on clickable photoshop images(or just icons?)

**Comment by mariabrock** [comment]
NavBar:
https://getbootstrap.com/docs/4.3/components/navbar/#external-content

* the drop-down menu is a wireframe that will be submitted below

Imperial Style Guide:
https://imperialstyleguide.com/

bootstrap css source code:
https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.css

**Comment by mariabrock** [comment]
![dropdown-menu-together](https://user-images.githubusercontent.com/54127296/69000148-d6c88600-0890-11ea-9642-a23012d94a00.PNG)
