### ISSUE TITLE
Personnel: Seed Data

### ISSUE THREAD

**Issue by EmileeA** [nss-evening-cohort-10/nutshell-star-destroyer#36]
# User Story
WHEN I open my database
THEN I should see personnel data present.

# AC
WHEN I go to the repo
THEN I should see a db folder
AND the personnel data

# Dev Notes
Create a personnel.json file and base.json file containing 
`{
  "person1": {
  "id": "person1",
  "name": "Stormtrooper",
  "secorId": "",
  "weaponId": "weapon1"
  },
  "person2": {
  "id": "person2",
  "name": "Imperial Officer",
  "secorId": "",
  "weaponId": "weapon2"
  },
  "person3": {
  "id": "person3",
  "name": "TIE Fighter Pilot",
  "secorId": "",
  "weaponId": "weapon3"
  },
  "person4": {
  "id": "person4",
  "name": "Star Gunner",
  "secorId": "",
  "weaponId": "weapon4"
  }
  }`
and base.json:
`{
  "enemies": "enemies",
  "personnel": "personnel",
  "sectors": "sectors",
  "weapons": "weapons"
}`

**Comment by mariabrock** [comment]
![personnel wireframe](https://user-images.githubusercontent.com/54127296/68828893-c637c600-066c-11ea-8713-9ba06b967301.PNG)
