### ISSUE TITLE
Authentication-Login

### ISSUE THREAD

**Issue by EmileeA** [nss-evening-cohort-10/nutshell-star-destroyer#37]
# User Stories
As a user, I should be able to login via google.

# Dev Notes
* Firebase API keys should be added to the project during Setup
* In Firebase, set up sign-in method for users to sign in using Google credentials
* On the home page create a Google button (that lives with the navbar) to click for login.
*  In src >> components >> auth >> auth.js write a function signMeIn that uses a popup to sign in with Google through Firebase
*  Write a function authStringBuilder that adds an eventlistener to the Google auth button on the dashboard home screen and calls signMeIn on click
*The Logout button will hide when logged out, and the login button will hide when logged in.

**Comment by ghost** [comment]
Authentication works. Existing Google login square needs to be changed to a login button and moved into the navbar. Need to update Logout button to hide when logged out, and hide login button when logged in.
