### ISSUE TITLE
ERD

### ISSUE THREAD

**Issue by EmileeA** [nss-evening-cohort-10/nutshell-star-destroyer#8]

**Comment by EmileeA** [comment]
![Star Destroyer (1)](https://user-images.githubusercontent.com/36553398/68726781-23a61700-0588-11ea-9631-899fd0881fd8.png)

**Comment by ghost** [comment]
<img width="560" alt="nutshellSecondaryERD" src="https://user-images.githubusercontent.com/54124397/69482511-14be3080-0de2-11ea-9a71-5445934db58b.PNG">
